spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show_sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show_sql: false
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

image-storage-dir: C:\Users\PC\Documents\ProjetsDev\Benevoles